# -*- Dockerfile -*-

FROM ghcr.io/r-hub/r-musl-libs-common AS common
FROM ubuntu:18.04 AS build
COPY --from=common /opt/r-lib /opt/r-lib

RUN apt-get update && \
    apt-get install -y build-essential g++ gfortran curl \
    pkg-config

# need to build libcurl on bionic, otherwise it crashes
RUN rm -rf /opt/r-lib/bin/curl* /opt/r-lib/include/curl \
    opt/r-lib/lib/libcurl.a \
    opt/r-lib/lib/pkgconfig/libcurl.pc \
    opt/r-lib/share/aclocal/libcurl.m4
RUN curl -LO https://curl.haxx.se/download/curl-8.11.0.tar.gz
RUN tar xzf curl-*.tar.gz && rm curl-*.tar.gz
RUN cd curl-* && \
    PKG_CONFIG_PATH=/opt/r-lib/lib/pkgconfig \
    ./configure --prefix=/opt/r-lib \
      --enable-static --disable-shared --with-openssl \
      --without-libpsl --without-brotli; \
    make && \
    make install

FROM ubuntu:18.04
COPY --from=build /opt/r-lib /opt/-rlib

# Some of this info is shown on the GH packages pages
LABEL org.opencontainers.image.source="https://github.com/r-hub/r-musl"
LABEL org.opencontainers.image.description="Self-contained R build for GNU/Linux, system libraries"
LABEL org.opencontainers.image.authors="https://github.com/gaborcsardi"
