# -*- Dockerfile -*-

FROM ghcr.io/r-hub/r-musl-libs-common

RUN apk add c-ares-r curl-r libcurl-r

# Some of this info is shown on the GH packages pages
LABEL org.opencontainers.image.source="https://github.com/r-hub/r-musl"
LABEL org.opencontainers.image.description="Self-contained R build for Alpine Linux. System libraries."
LABEL org.opencontainers.image.authors="https://github.com/gaborcsardi"
