# -*- Dockerfile -*-

FROM ghcr.io/r-hub/r-musl-libs-bionic AS libs
FROM ubuntu:18.04 AS build

USER root
WORKDIR /root

RUN apt-get update && \
    apt-get install -y build-essential g++ gfortran curl \
    pkg-config

COPY --from=libs /opt/r-lib /opt/r-lib

RUN curl -LO https://cran.r-project.org/src/base/R-4/R-4.4.2.tar.gz
RUN tar xzf R-4.4.2.tar.gz

ENV TZ=UTC

COPY R-4.4.2-bionic.patch /root/
RUN apt-get install -y patch
RUN cd R-4.4.2 && patch -p1 < ../R-4.4.2-bionic.patch

# which is missing from the Alma Linux 8 container, so we include a static copy 
RUN mkdir -p /opt/R/4.4.2-static/lib/R/tools && \
    cp /opt/r-lib/bin/which /opt/R/4.4.2-static/lib/R/tools/

# also include static patchelf, needed on x86_64 to remove unneeded dynamic libs
RUN cp /opt/r-lib/bin/patchelf /opt/R/4.4.2-static/lib/R/tools/

RUN cd R-4.4.2 && \
    export PATH=/opt/R/4.4.2-static/lib/R/tools:/opt/r-lib/bin:$PATH && \
    if [ "`arch`" = "x86_64" ]; then QUAD="/usr/lib/libquadmath.a"; fi && \
    ./configure --with-internal-tzcode --prefix=/opt/R/4.4.2-static --with-x=no \
      --disable-openmp --with-blas=/opt/r-lib/lib/libopenblas.a \
      --enable-BLAS-shlib=no --with-lapack \
      --with-static-cairo --with-included-gettext \
      CPPFLAGS=-I/opt/r-lib/include \
      LDFLAGS=-L/opt/r-lib/lib \
      BLAS_HOME='/opt/r-lib/lib/libopenblas.a' \
      FLIBS="/usr/lib/gcc/aarch64-linux-gnu/7/libgfortran.a $QUAD -lpthread" \
      PKG_CONFIG_PATH=/opt/r-lib/lib/pkgconfig

RUN cd R-4.4.2 && make
RUN cd R-4.4.2 && make install

# patch to embed CA certs
RUN curl -L https://curl.se/ca/cacert.pem -o /opt/R/4.4.2-static/lib/R/share/curl-ca-bundle.crt
RUN echo "CURL_CA_BUNDLE=${CURL_CA_BUNDLE-/opt/R/4.4.2-static/lib/R/share/curl-ca-bundle.crt}" \
    >> /opt/R/4.4.2-static/lib/R/etc/Renviron

# strip
RUN for f in `find /opt/R/4.4.2-static/ -executable -type f `; do strip -x "$f" || true; done

FROM ubuntu:18.04 AS final
COPY --from=build /opt/R/4.4.2-static /opt/R/4.4.2-static

USER root
WORKDIR /root

ENV TZ=UTC

# Some of this info is shown on the GH packages pages
LABEL org.opencontainers.image.source="https://github.com/r-hub/r-musl"
LABEL org.opencontainers.image.description="Self-contained R build for GNU/Linux"
LABEL org.opencontainers.image.authors="https://github.com/gaborcsardi"
